// Code generated by goyacc -o parser.go parser.go.y. DO NOT EDIT.

//line parser.go.y:2
package sql

import __yyfmt__ "fmt"

//line parser.go.y:2

//line parser.go.y:5
type yySymType struct {
	yys                  int
	literal              string
	identifier           string
	signedNumber         int64
	statement            interface{}
	columnNameList       []string
	columnName           string
	columnDefList        []ColumnDef
	columnDef            ColumnDef
	indexedColumnList    []IndexedColumn
	indexedColumn        IndexedColumn
	name                 string
	withoutRowid         bool
	unique               bool
	bool                 bool
	collate              string
	sortOrder            SortOrder
	columnConstraint     columnConstraint
	columnConstraintList []columnConstraint
	tableConstraint      TableConstraint
	tableConstraintList  []TableConstraint
	foreignKeyClause     ForeignKeyClause
	triggerAction        TriggerAction
	trigger              Trigger
	triggerList          []Trigger
	where                Expression
	expr                 Expression
	exprList             []Expression
	float                float64
}

const ABORT = 57346
const ACTION = 57347
const AND = 57348
const ASC = 57349
const AUTOINCREMENT = 57350
const CASCADE = 57351
const CHECK = 57352
const COLLATE = 57353
const CONFLICT = 57354
const CONSTRAINT = 57355
const CREATE = 57356
const DEFAULT = 57357
const DEFERRABLE = 57358
const DEFERRED = 57359
const DELETE = 57360
const DESC = 57361
const FAIL = 57362
const FOREIGN = 57363
const FROM = 57364
const GLOB = 57365
const IGNORE = 57366
const IN = 57367
const INDEX = 57368
const INITIALLY = 57369
const IS = 57370
const KEY = 57371
const LIKE = 57372
const MATCH = 57373
const NO = 57374
const NOT = 57375
const NULL = 57376
const ON = 57377
const OR = 57378
const PRIMARY = 57379
const REFERENCES = 57380
const REGEXP = 57381
const REPLACE = 57382
const RESTRICT = 57383
const ROLLBACK = 57384
const ROWID = 57385
const SELECT = 57386
const SET = 57387
const TABLE = 57388
const UNIQUE = 57389
const UPDATE = 57390
const WHERE = 57391
const WITHOUT = 57392
const tBare = 57393
const tLiteral = 57394
const tIdentifier = 57395
const tOperator = 57396
const tSignedNumber = 57397
const tFloat = 57398

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"ABORT",
	"ACTION",
	"AND",
	"ASC",
	"AUTOINCREMENT",
	"CASCADE",
	"CHECK",
	"COLLATE",
	"CONFLICT",
	"CONSTRAINT",
	"CREATE",
	"DEFAULT",
	"DEFERRABLE",
	"DEFERRED",
	"DELETE",
	"DESC",
	"FAIL",
	"FOREIGN",
	"FROM",
	"GLOB",
	"IGNORE",
	"IN",
	"INDEX",
	"INITIALLY",
	"IS",
	"KEY",
	"LIKE",
	"MATCH",
	"NO",
	"NOT",
	"NULL",
	"ON",
	"OR",
	"PRIMARY",
	"REFERENCES",
	"REGEXP",
	"REPLACE",
	"RESTRICT",
	"ROLLBACK",
	"ROWID",
	"SELECT",
	"SET",
	"TABLE",
	"UNIQUE",
	"UPDATE",
	"WHERE",
	"WITHOUT",
	"tBare",
	"tLiteral",
	"tIdentifier",
	"tOperator",
	"tSignedNumber",
	"tFloat",
	"'-'",
	"'+'",
	"','",
	"'('",
	"')'",
	"'*'",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 92,
	60, 6,
	-2, 95,
	-1, 93,
	60, 7,
	-2, 96,
}

const yyPrivate = 57344

const yyLast = 231

var yyAct = [...]uint8{
	175, 88, 86, 51, 9, 130, 89, 11, 83, 70,
	116, 84, 100, 119, 118, 152, 90, 20, 117, 124,
	11, 23, 150, 25, 159, 87, 11, 122, 120, 28,
	34, 34, 36, 11, 109, 112, 28, 156, 155, 31,
	154, 60, 92, 91, 93, 56, 72, 75, 73, 74,
	96, 94, 78, 67, 79, 116, 68, 55, 119, 118,
	80, 116, 144, 117, 119, 118, 69, 12, 127, 117,
	103, 150, 112, 151, 146, 13, 53, 14, 71, 24,
	104, 106, 112, 173, 113, 111, 10, 110, 104, 106,
	105, 107, 40, 63, 41, 76, 77, 121, 43, 72,
	75, 73, 74, 19, 135, 123, 72, 98, 81, 82,
	13, 11, 14, 174, 131, 99, 39, 52, 132, 138,
	139, 140, 141, 143, 133, 137, 11, 136, 66, 131,
	147, 145, 72, 75, 73, 74, 29, 37, 153, 12,
	18, 64, 6, 29, 76, 77, 12, 13, 177, 14,
	59, 12, 11, 64, 13, 162, 14, 169, 163, 13,
	42, 14, 182, 165, 48, 50, 57, 15, 17, 49,
	167, 179, 5, 170, 27, 180, 58, 171, 61, 158,
	178, 181, 33, 30, 176, 97, 95, 46, 45, 65,
	149, 44, 52, 172, 21, 168, 54, 101, 8, 161,
	129, 47, 39, 164, 115, 126, 38, 183, 157, 102,
	148, 128, 35, 142, 85, 134, 160, 22, 166, 32,
	125, 114, 62, 16, 26, 7, 108, 4, 3, 2,
	1,
}

var yyPact = [...]int16{
	128, -32768, -32768, -32768, -32768, 24, 121, 81, -32768, -32768,
	-32768, -32768, -32768, -32768, -32768, 59, 168, -32768, 24, 59,
	19, 59, -32768, -32768, 96, 148, -20, -32768, 59, 59,
	59, 103, 33, 154, 16, 154, -3, 129, -32768, 59,
	189, 43, 154, -32768, 160, -32768, 94, -32768, -7, 44,
	59, -32768, 59, 51, 154, -9, -32768, 157, -10, 156,
	-32768, 129, -32768, 72, -32768, 190, -32768, -9, -32768, -32768,
	-32768, -32768, -32768, 77, 77, -32768, -32768, -32768, -32768, -26,
	26, 51, 51, 23, -32768, 193, -44, -32768, -32, -32768,
	-32768, -32768, -32768, -32768, -9, -33, -9, -41, -32768, -32768,
	197, -32768, -32768, 7, -32768, -32768, -32768, -32768, 184, 108,
	-32768, 51, -9, 55, 190, 93, -9, -9, -9, -9,
	-9, 1, -9, 13, 108, -32768, -32768, -32768, 163, -32768,
	12, -32768, -46, -32768, -32768, -9, -32768, -32768, -44, -44,
	-44, -44, -21, -44, -32768, -24, 144, -37, -32768, 182,
	108, -32768, -32768, -44, -32768, -9, -32768, -32768, 191, 79,
	135, -32768, -32768, -44, 153, -32768, -32768, 65, -32768, -32768,
	-32768, -32768, -32768, 139, 139, -32768, 147, -32768, -32768, 202,
	-32768, -32768, -32768, -32768,
}

var yyPgo = [...]uint8{
	0, 230, 229, 228, 227, 1, 9, 6, 16, 4,
	198, 5, 226, 225, 224, 174, 8, 11, 182, 137,
	223, 222, 221, 12, 220, 98, 160, 45, 219, 3,
	0, 218, 216, 215, 214, 2, 213, 211, 210, 208,
}

var yyR1 = [...]int8{
	0, 1, 1, 1, 6, 6, 5, 5, 7, 7,
	7, 8, 8, 8, 9, 9, 11, 11, 12, 10,
	10, 13, 13, 25, 25, 25, 25, 25, 25, 25,
	25, 25, 25, 25, 26, 26, 26, 27, 27, 27,
	29, 19, 19, 28, 28, 28, 24, 24, 14, 14,
	15, 15, 18, 18, 18, 18, 22, 22, 23, 23,
	23, 21, 21, 20, 20, 39, 39, 39, 39, 39,
	39, 16, 16, 34, 17, 30, 30, 30, 30, 30,
	31, 31, 32, 32, 37, 37, 38, 38, 33, 33,
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
	35, 35, 36, 36, 36, 2, 3, 4,
}

var yyR2 = [...]int8{
	0, 1, 1, 1, 1, 1, 1, 1, 1, 2,
	2, 1, 2, 2, 1, 1, 1, 3, 3, 1,
	1, 1, 3, 4, 1, 2, 1, 4, 2, 2,
	2, 2, 2, 1, 0, 1, 2, 5, 5, 6,
	6, 0, 2, 0, 3, 4, 0, 1, 1, 3,
	3, 3, 0, 1, 4, 6, 0, 2, 0, 1,
	1, 0, 2, 0, 1, 0, 3, 3, 3, 3,
	3, 1, 3, 1, 3, 2, 2, 1, 1, 2,
	3, 3, 0, 2, 0, 1, 0, 2, 0, 2,
	1, 4, 1, 1, 1, 1, 1, 3, 3, 3,
	3, 3, 0, 1, 3, 4, 8, 10,
}

var yyChk = [...]int16{
	-32768, -1, -2, -3, -4, 44, 14, -13, -10, -9,
	62, -5, 43, 51, 53, 46, -20, 47, 59, 22,
	-5, 26, -10, -5, 60, -5, -14, -15, -9, 40,
	35, 59, -28, -18, -5, -18, -5, -19, -15, 13,
	59, 61, -26, -25, 37, 34, 33, 47, 10, 15,
	11, -29, 38, 60, -26, 60, -27, 37, 47, 21,
	-5, -19, -21, 50, -25, 29, 34, 60, -7, -8,
	-6, 34, 55, 57, 58, 56, 51, 52, -5, -5,
	-7, 57, 58, -16, -17, -34, -35, 34, -5, -7,
	-8, 52, 51, 53, 60, 29, 60, 29, -27, 43,
	-23, 7, 19, -35, -7, -8, -7, -8, -12, 60,
	61, 59, 59, 61, -22, 11, 54, 62, 58, 57,
	60, -35, 60, -16, 60, -24, 8, 61, -37, 16,
	-11, -9, -7, -17, -33, 49, -23, -6, -35, -35,
	-35, -35, -36, -35, 61, -16, 61, -11, -38, 27,
	59, 61, 61, -35, 61, 59, 61, -39, 35, 61,
	-32, 17, -9, -35, 12, -29, -31, 35, 42, 4,
	20, 24, 40, 18, 48, -30, 45, 9, 41, 32,
	-30, 34, 15, 5,
}

var yyDef = [...]int8{
	0, -2, 1, 2, 3, 0, 63, 0, 21, 19,
	20, 14, 15, 6, 7, 0, 0, 64, 0, 0,
	0, 0, 22, 105, 0, 0, 43, 48, 52, 52,
	0, 41, 0, 34, 53, 34, 0, 0, 49, 0,
	41, 61, 50, 35, 0, 24, 0, 26, 0, 0,
	0, 33, 0, 0, 51, 0, 44, 0, 0, 0,
	42, 0, 106, 0, 36, 58, 25, 0, 28, 29,
	30, 31, 8, 0, 0, 11, 4, 5, 32, 0,
	0, 0, 0, 0, 71, 56, 73, 90, 0, 92,
	93, 94, -2, -2, 0, 0, 0, 0, 45, 62,
	46, 59, 60, 0, 9, 12, 10, 13, 84, 0,
	54, 0, 0, 88, 58, 0, 0, 0, 0, 0,
	102, 0, 0, 0, 0, 23, 47, 27, 86, 85,
	0, 16, 0, 72, 107, 0, 74, 57, 97, 98,
	99, 100, 0, 103, 101, 0, 65, 0, 82, 0,
	0, 18, 55, 89, 91, 0, 37, 38, 0, 0,
	40, 87, 17, 104, 0, 39, 83, 0, 66, 67,
	68, 69, 70, 0, 0, 80, 0, 77, 78, 0,
	81, 75, 76, 79,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	60, 61, 62, 58, 59, 57,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -32768

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:131
		{
			yyVAL.literal = yyDollar[1].identifier
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:134
		{
			yyVAL.literal = yyDollar[1].identifier
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:139
		{
			yyVAL.identifier = yyDollar[1].identifier
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:142
		{
			yyVAL.identifier = yyDollar[1].identifier
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:147
		{
			yyVAL.signedNumber = yyDollar[1].signedNumber
		}
	case 9:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:150
		{
			yyVAL.signedNumber = -yyDollar[2].signedNumber
		}
	case 10:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:153
		{
			yyVAL.signedNumber = yyDollar[2].signedNumber
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:158
		{
			yyVAL.float = yyDollar[1].float
		}
	case 12:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:161
		{
			yyVAL.float = -yyDollar[2].float
		}
	case 13:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:164
		{
			yyVAL.float = yyDollar[2].float
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:169
		{
			yyVAL.columnName = yyDollar[1].identifier
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:172
		{
			yyVAL.columnName = "ROWID"
		}
	case 16:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:177
		{
			yyVAL.columnNameList = []string{yyDollar[1].columnName}
		}
	case 17:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:180
		{
			yyVAL.columnNameList = append(yyDollar[1].columnNameList, yyDollar[3].columnName)
		}
	case 18:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:185
		{
			yyVAL.columnNameList = yyDollar[2].columnNameList
		}
	case 19:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:190
		{
			yyVAL.columnName = yyDollar[1].columnName
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:193
		{
			yyVAL.columnName = "*"
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:198
		{
			yyVAL.columnNameList = []string{yyDollar[1].columnName}
		}
	case 22:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:201
		{
			yyVAL.columnNameList = append(yyDollar[1].columnNameList, yyDollar[3].columnName)
		}
	case 23:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:207
		{
			yyVAL.columnConstraint = ccPrimaryKey{yyDollar[3].sortOrder, yyDollar[4].bool}
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:210
		{
			yyVAL.columnConstraint = ccNull(true)
		}
	case 25:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:213
		{
			yyVAL.columnConstraint = ccNull(false)
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:216
		{
			yyVAL.columnConstraint = ccUnique(true)
		}
	case 27:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:219
		{
			yyVAL.columnConstraint = ccCheck{expr: yyDollar[3].expr}
		}
	case 28:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:222
		{
			yyVAL.columnConstraint = ccDefault(yyDollar[2].signedNumber)
		}
	case 29:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:225
		{
			yyVAL.columnConstraint = ccDefault(yyDollar[2].float)
		}
	case 30:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:228
		{
			yyVAL.columnConstraint = ccDefault(yyDollar[2].literal)
		}
	case 31:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:231
		{
			yyVAL.columnConstraint = ccDefault(nil)
		}
	case 32:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:234
		{
			yyVAL.columnConstraint = ccCollate(yyDollar[2].identifier)
		}
	case 33:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:237
		{
			yyVAL.columnConstraint = ccReferences(yyDollar[1].foreignKeyClause)
		}
	case 34:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:242
		{
			yyVAL.columnConstraintList = nil
		}
	case 35:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:245
		{
			yyVAL.columnConstraintList = []columnConstraint{yyDollar[1].columnConstraint}
		}
	case 36:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:248
		{
			yyVAL.columnConstraintList = append(yyDollar[1].columnConstraintList, yyDollar[2].columnConstraint)
		}
	case 37:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:253
		{
			yyVAL.tableConstraint = TablePrimaryKey{yyDollar[4].indexedColumnList}
		}
	case 38:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:256
		{
			yyVAL.tableConstraint = TableUnique{
				IndexedColumns: yyDollar[3].indexedColumnList,
			}
		}
	case 39:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.go.y:261
		{
			yyVAL.tableConstraint = TableForeignKey{
				Columns: yyDollar[4].columnNameList,
				Clause:  yyDollar[6].foreignKeyClause,
			}
		}
	case 40:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.go.y:269
		{
			yyVAL.foreignKeyClause = ForeignKeyClause{
				ForeignTable:      yyDollar[2].identifier,
				ForeignColumns:    yyDollar[3].columnNameList,
				Deferrable:        yyDollar[4].bool,
				InitiallyDeferred: yyDollar[5].bool,
				Triggers:          yyDollar[6].triggerList,
			}
		}
	case 41:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:280
		{
		}
	case 42:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:281
		{
		}
	case 43:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:285
		{
		}
	case 44:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:286
		{
			yyVAL.tableConstraintList = []TableConstraint{yyDollar[3].tableConstraint}
		}
	case 45:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:289
		{
			yyVAL.tableConstraintList = append(yyDollar[1].tableConstraintList, yyDollar[4].tableConstraint)
		}
	case 46:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:295
		{
		}
	case 47:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:296
		{
			yyVAL.bool = true
		}
	case 48:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:301
		{
			yyVAL.columnDefList = []ColumnDef{yyDollar[1].columnDef}
		}
	case 49:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:304
		{
			yyVAL.columnDefList = append(yyDollar[1].columnDefList, yyDollar[3].columnDef)
		}
	case 50:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:309
		{
			yyVAL.columnDef = makeColumnDef(yyDollar[1].columnName, yyDollar[2].name, yyDollar[3].columnConstraintList)
		}
	case 51:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:312
		{
			yyVAL.columnDef = makeColumnDef("REPLACE", yyDollar[2].name, yyDollar[3].columnConstraintList)
		}
	case 52:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:317
		{
			yyVAL.name = ""
		}
	case 53:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:320
		{
			yyVAL.name = yyDollar[1].identifier
		}
	case 54:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:323
		{
			yyVAL.name = yyDollar[1].identifier
		}
	case 55:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.go.y:326
		{
			yyVAL.name = yyDollar[1].identifier
		}
	case 56:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:331
		{
		}
	case 57:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:332
		{
			yyVAL.collate = yyDollar[2].literal
		}
	case 58:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:337
		{
			yyVAL.sortOrder = Asc
		}
	case 59:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:340
		{
			yyVAL.sortOrder = Asc
		}
	case 60:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:343
		{
			yyVAL.sortOrder = Desc
		}
	case 61:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:348
		{
			yyVAL.withoutRowid = false
		}
	case 62:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:351
		{
			yyVAL.withoutRowid = true
		}
	case 63:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:356
		{
			yyVAL.unique = false
		}
	case 64:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:359
		{
			yyVAL.unique = true
		}
	case 65:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:364
		{
		}
	case 66:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:365
		{
		}
	case 67:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:367
		{
		}
	case 68:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:369
		{
		}
	case 69:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:371
		{
		}
	case 70:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:373
		{
		}
	case 71:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:377
		{
			yyVAL.indexedColumnList = []IndexedColumn{yyDollar[1].indexedColumn}
		}
	case 72:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:380
		{
			yyVAL.indexedColumnList = append(yyDollar[1].indexedColumnList, yyDollar[3].indexedColumn)
		}
	case 73:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:385
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 74:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:390
		{
			yyVAL.indexedColumn = newIndexColumn(yyDollar[1].expr, yyDollar[2].collate, yyDollar[3].sortOrder)
		}
	case 75:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:395
		{
			yyVAL.triggerAction = ActionSetNull
		}
	case 76:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:398
		{
			yyVAL.triggerAction = ActionSetDefault
		}
	case 77:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:401
		{
			yyVAL.triggerAction = ActionCascade
		}
	case 78:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:404
		{
			yyVAL.triggerAction = ActionRestrict
		}
	case 79:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:407
		{
			yyVAL.triggerAction = ActionNoAction
		}
	case 80:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:412
		{
			yyVAL.trigger = TriggerOnDelete(yyDollar[3].triggerAction)
		}
	case 81:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:415
		{
			yyVAL.trigger = TriggerOnUpdate(yyDollar[3].triggerAction)
		}
	case 82:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:420
		{
		}
	case 83:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:421
		{
			yyVAL.triggerList = append(yyDollar[1].triggerList, yyDollar[2].trigger)
		}
	case 84:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:426
		{
			yyVAL.bool = false
		}
	case 85:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:429
		{
			yyVAL.bool = true
		}
	case 86:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:434
		{
			yyVAL.bool = false
		}
	case 87:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:437
		{
			yyVAL.bool = true
		}
	case 88:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:442
		{
		}
	case 89:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:443
		{
			yyVAL.where = yyDollar[2].expr
		}
	case 90:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:448
		{
			yyVAL.expr = nil
		}
	case 91:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:451
		{
			yyVAL.expr = ExFunction{yyDollar[1].identifier, yyDollar[3].exprList}
		}
	case 92:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:454
		{
			yyVAL.expr = yyDollar[1].signedNumber
		}
	case 93:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:457
		{
			yyVAL.expr = yyDollar[1].float
		}
	case 94:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:460
		{
			yyVAL.expr = yyDollar[1].identifier
		}
	case 95:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:463
		{
			yyVAL.expr = ExColumn(yyDollar[1].identifier)
		}
	case 96:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:466
		{
			yyVAL.expr = ExColumn(yyDollar[1].identifier)
		}
	case 97:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:469
		{
			yyVAL.expr = ExBinaryOp{yyDollar[2].identifier, yyDollar[1].expr, yyDollar[3].expr}
		}
	case 98:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:472
		{
			yyVAL.expr = ExBinaryOp{"*", yyDollar[1].expr, yyDollar[3].expr}
		}
	case 99:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:475
		{
			yyVAL.expr = ExBinaryOp{"+", yyDollar[1].expr, yyDollar[3].expr}
		}
	case 100:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:478
		{
			yyVAL.expr = ExBinaryOp{"-", yyDollar[1].expr, yyDollar[3].expr}
		}
	case 101:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:481
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 102:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:486
		{
			yyVAL.exprList = nil
		}
	case 103:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:489
		{
			yyVAL.exprList = []Expression{yyDollar[1].expr}
		}
	case 104:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:492
		{
			yyVAL.exprList = append(yyDollar[1].exprList, yyDollar[3].expr)
		}
	case 105:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:497
		{
			yylex.(*lexer).result = SelectStmt{Columns: yyDollar[2].columnNameList, Table: yyDollar[4].identifier}
		}
	case 106:
		yyDollar = yyS[yypt-8 : yypt+1]
//line parser.go.y:502
		{
			yylex.(*lexer).result = CreateTableStmt{
				Table:        yyDollar[3].identifier,
				Columns:      yyDollar[5].columnDefList,
				Constraints:  yyDollar[6].tableConstraintList,
				WithoutRowid: yyDollar[8].withoutRowid,
			}
		}
	case 107:
		yyDollar = yyS[yypt-10 : yypt+1]
//line parser.go.y:512
		{
			yylex.(*lexer).result = CreateIndexStmt{
				Index:          yyDollar[4].identifier,
				Table:          yyDollar[6].identifier,
				Unique:         yyDollar[2].unique,
				IndexedColumns: yyDollar[8].indexedColumnList,
				Where:          yyDollar[10].where,
			}
		}
	}
	goto yystack /* stack new state and value */
}
